// AUTO-GENERATED by scripts/build_template_index.py -- DO NOT EDIT MANUALLY
import { TemplateWithData, TemplateGroupSettings, createTemplateEntry, TemplateLayoutsWithSettings } from "./utils";

import { templates as arcticIceTemplates, settings as arcticIceSettings } from "./arctic-ice";
import { templates as blueprintTemplates, settings as blueprintSettings } from "./blueprint";
import { templates as botanicalTemplates, settings as botanicalSettings } from "./botanical";
import { templates as candyPastelTemplates, settings as candyPastelSettings } from "./candy-pastel";
import { templates as chalkPastelTemplates, settings as chalkPastelSettings } from "./chalk-pastel";
import { templates as chalkboardTemplates, settings as chalkboardSettings } from "./chalkboard";
import { templates as concreteIndustrialTemplates, settings as concreteIndustrialSettings } from "./concrete-industrial";
import { templates as darkCorporateTemplates, settings as darkCorporateSettings } from "./dark-corporate";
import { templates as generalTemplates, settings as generalSettings } from "./general";
import { templates as glassmorphismTemplates, settings as glassmorphismSettings } from "./glassmorphism";
import { templates as luxuryGoldTemplates, settings as luxuryGoldSettings } from "./luxury-gold";
import { templates as magazineEditorialTemplates, settings as magazineEditorialSettings } from "./magazine-editorial";
import { templates as minimalistZenTemplates, settings as minimalistZenSettings } from "./minimalist-zen";
import { templates as modernTemplates, settings as modernSettings } from "./modern";
import { templates as natureForestTemplates, settings as natureForestSettings } from "./nature-forest";
import { templates as neoGeneralTemplates, settings as neoGeneralSettings } from "./neo-general";
import { templates as neoModernTemplates, settings as neoModernSettings } from "./neo-modern";
import { templates as neoStandardTemplates, settings as neoStandardSettings } from "./neo-standard";
import { templates as neoSwiftTemplates, settings as neoSwiftSettings } from "./neo-swift";
import { templates as neonCyberpunkTemplates, settings as neonCyberpunkSettings } from "./neon-cyberpunk";
import { templates as newspaperTemplates, settings as newspaperSettings } from "./newspaper";
import { templates as oceanDeepTemplates, settings as oceanDeepSettings } from "./ocean-deep";
import { templates as pixelRetroTemplates, settings as pixelRetroSettings } from "./pixel-retro";
import { templates as retroSynthwaveTemplates, settings as retroSynthwaveSettings } from "./retro-synthwave";
import { templates as standardTemplates, settings as standardSettings } from "./standard";
import { templates as starfieldTemplates, settings as starfieldSettings } from "./starfield";
import { templates as sunsetWarmTemplates, settings as sunsetWarmSettings } from "./sunset-warm";
import { templates as swiftTemplates, settings as swiftSettings } from "./swift";
import { templates as terracottaTemplates, settings as terracottaSettings } from "./terracotta";
import { templates as vintagePaperTemplates, settings as vintagePaperSettings } from "./vintage-paper";
import { templates as watercolorTemplates, settings as watercolorSettings } from "./watercolor";


export const allLayouts: TemplateWithData[] = [
    ...arcticIceTemplates,
    ...blueprintTemplates,
    ...botanicalTemplates,
    ...candyPastelTemplates,
    ...chalkPastelTemplates,
    ...chalkboardTemplates,
    ...concreteIndustrialTemplates,
    ...darkCorporateTemplates,
    ...generalTemplates,
    ...glassmorphismTemplates,
    ...luxuryGoldTemplates,
    ...magazineEditorialTemplates,
    ...minimalistZenTemplates,
    ...modernTemplates,
    ...natureForestTemplates,
    ...neoGeneralTemplates,
    ...neoModernTemplates,
    ...neoStandardTemplates,
    ...neoSwiftTemplates,
    ...neonCyberpunkTemplates,
    ...newspaperTemplates,
    ...oceanDeepTemplates,
    ...pixelRetroTemplates,
    ...retroSynthwaveTemplates,
    ...standardTemplates,
    ...starfieldTemplates,
    ...sunsetWarmTemplates,
    ...swiftTemplates,
    ...terracottaTemplates,
    ...vintagePaperTemplates,
    ...watercolorTemplates,
];


export const templates: TemplateLayoutsWithSettings[] = [
    {
        id: "arctic-ice",
        name: "Arctic Ice",
        description: arcticIceSettings.description,
        settings: arcticIceSettings as TemplateGroupSettings,
        layouts: arcticIceTemplates,
    },
    {
        id: "blueprint",
        name: "Blueprint",
        description: blueprintSettings.description,
        settings: blueprintSettings as TemplateGroupSettings,
        layouts: blueprintTemplates,
    },
    {
        id: "botanical",
        name: "Botanical",
        description: botanicalSettings.description,
        settings: botanicalSettings as TemplateGroupSettings,
        layouts: botanicalTemplates,
    },
    {
        id: "candy-pastel",
        name: "Candy Pastel",
        description: candyPastelSettings.description,
        settings: candyPastelSettings as TemplateGroupSettings,
        layouts: candyPastelTemplates,
    },
    {
        id: "chalk-pastel",
        name: "Chalk Pastel",
        description: chalkPastelSettings.description,
        settings: chalkPastelSettings as TemplateGroupSettings,
        layouts: chalkPastelTemplates,
    },
    {
        id: "chalkboard",
        name: "Chalkboard",
        description: chalkboardSettings.description,
        settings: chalkboardSettings as TemplateGroupSettings,
        layouts: chalkboardTemplates,
    },
    {
        id: "concrete-industrial",
        name: "Concrete Industrial",
        description: concreteIndustrialSettings.description,
        settings: concreteIndustrialSettings as TemplateGroupSettings,
        layouts: concreteIndustrialTemplates,
    },
    {
        id: "dark-corporate",
        name: "Dark Corporate",
        description: darkCorporateSettings.description,
        settings: darkCorporateSettings as TemplateGroupSettings,
        layouts: darkCorporateTemplates,
    },
    {
        id: "general",
        name: "General",
        description: generalSettings.description,
        settings: generalSettings as TemplateGroupSettings,
        layouts: generalTemplates,
    },
    {
        id: "glassmorphism",
        name: "Glassmorphism",
        description: glassmorphismSettings.description,
        settings: glassmorphismSettings as TemplateGroupSettings,
        layouts: glassmorphismTemplates,
    },
    {
        id: "luxury-gold",
        name: "Luxury Gold",
        description: luxuryGoldSettings.description,
        settings: luxuryGoldSettings as TemplateGroupSettings,
        layouts: luxuryGoldTemplates,
    },
    {
        id: "magazine-editorial",
        name: "Magazine Editorial",
        description: magazineEditorialSettings.description,
        settings: magazineEditorialSettings as TemplateGroupSettings,
        layouts: magazineEditorialTemplates,
    },
    {
        id: "minimalist-zen",
        name: "Minimalist Zen",
        description: minimalistZenSettings.description,
        settings: minimalistZenSettings as TemplateGroupSettings,
        layouts: minimalistZenTemplates,
    },
    {
        id: "modern",
        name: "Modern",
        description: modernSettings.description,
        settings: modernSettings as TemplateGroupSettings,
        layouts: modernTemplates,
    },
    {
        id: "nature-forest",
        name: "Nature Forest",
        description: natureForestSettings.description,
        settings: natureForestSettings as TemplateGroupSettings,
        layouts: natureForestTemplates,
    },
    {
        id: "neo-general",
        name: "Neo General",
        description: neoGeneralSettings.description,
        settings: neoGeneralSettings as TemplateGroupSettings,
        layouts: neoGeneralTemplates,
    },
    {
        id: "neo-modern",
        name: "Neo Modern",
        description: neoModernSettings.description,
        settings: neoModernSettings as TemplateGroupSettings,
        layouts: neoModernTemplates,
    },
    {
        id: "neo-standard",
        name: "Neo Standard",
        description: neoStandardSettings.description,
        settings: neoStandardSettings as TemplateGroupSettings,
        layouts: neoStandardTemplates,
    },
    {
        id: "neo-swift",
        name: "Neo Swift",
        description: neoSwiftSettings.description,
        settings: neoSwiftSettings as TemplateGroupSettings,
        layouts: neoSwiftTemplates,
    },
    {
        id: "neon-cyberpunk",
        name: "Neon Cyberpunk",
        description: neonCyberpunkSettings.description,
        settings: neonCyberpunkSettings as TemplateGroupSettings,
        layouts: neonCyberpunkTemplates,
    },
    {
        id: "newspaper",
        name: "Newspaper",
        description: newspaperSettings.description,
        settings: newspaperSettings as TemplateGroupSettings,
        layouts: newspaperTemplates,
    },
    {
        id: "ocean-deep",
        name: "Ocean Deep",
        description: oceanDeepSettings.description,
        settings: oceanDeepSettings as TemplateGroupSettings,
        layouts: oceanDeepTemplates,
    },
    {
        id: "pixel-retro",
        name: "Pixel Retro",
        description: pixelRetroSettings.description,
        settings: pixelRetroSettings as TemplateGroupSettings,
        layouts: pixelRetroTemplates,
    },
    {
        id: "retro-synthwave",
        name: "Retro Synthwave",
        description: retroSynthwaveSettings.description,
        settings: retroSynthwaveSettings as TemplateGroupSettings,
        layouts: retroSynthwaveTemplates,
    },
    {
        id: "standard",
        name: "Standard",
        description: standardSettings.description,
        settings: standardSettings as TemplateGroupSettings,
        layouts: standardTemplates,
    },
    {
        id: "starfield",
        name: "Starfield",
        description: starfieldSettings.description,
        settings: starfieldSettings as TemplateGroupSettings,
        layouts: starfieldTemplates,
    },
    {
        id: "sunset-warm",
        name: "Sunset Warm",
        description: sunsetWarmSettings.description,
        settings: sunsetWarmSettings as TemplateGroupSettings,
        layouts: sunsetWarmTemplates,
    },
    {
        id: "swift",
        name: "Swift",
        description: swiftSettings.description,
        settings: swiftSettings as TemplateGroupSettings,
        layouts: swiftTemplates,
    },
    {
        id: "terracotta",
        name: "Terracotta",
        description: terracottaSettings.description,
        settings: terracottaSettings as TemplateGroupSettings,
        layouts: terracottaTemplates,
    },
    {
        id: "vintage-paper",
        name: "Vintage Paper",
        description: vintagePaperSettings.description,
        settings: vintagePaperSettings as TemplateGroupSettings,
        layouts: vintagePaperTemplates,
    },
    {
        id: "watercolor",
        name: "Watercolor",
        description: watercolorSettings.description,
        settings: watercolorSettings as TemplateGroupSettings,
        layouts: watercolorTemplates,
    },
];


// Helper to get templates by group ID
export function getTemplatesByTemplateName(templateId: string): TemplateWithData[] {
    const template = templates.find((t) => t.id === templateId);
    return template?.layouts || [];
}

export function getSchemaByTemplateId(templateId: string): any {
    const template = templates.find((t) => t.id === templateId);
    return template?.layouts.map(t => {
        return {
            id: t.layoutId,
            name: t.layoutName,
            description: t.layoutDescription,
            json_schema: t.schemaJSON,
        }
    }) || {};
}

export function getSettingsByTemplateId(templateId: string): TemplateGroupSettings | undefined {
    const template = templates.find((t) => t.id === templateId);
    return template?.settings || undefined;
}

// Helper to get template by layout ID
export function getTemplateByLayoutId(layoutId: string): TemplateWithData | undefined {
    return allLayouts.find((t) => t.layoutId === layoutId);
}

export function getLayoutByLayoutId(layout: string): TemplateWithData | undefined {
    const templateName = layout.split(':')[0]
    const template = templates.find((t) => t.id === templateName)
    if (template) {
        return template.layouts.find((t) => t.layoutId === layout);
    }
    return undefined;
}
