// AUTO-GENERATED by scripts/build_template_index.py -- DO NOT EDIT MANUALLY
import { TemplateWithData, TemplateGroupSettings, createTemplateEntry, TemplateLayoutsWithSettings } from "./utils";

import { templates as blueprintTemplates, settings as blueprintSettings } from "./blueprint";
import { templates as chalkboardTemplates, settings as chalkboardSettings } from "./chalkboard";
import { templates as generalTemplates, settings as generalSettings } from "./general";
import { templates as modernTemplates, settings as modernSettings } from "./modern";
import { templates as neoGeneralTemplates, settings as neoGeneralSettings } from "./neo-general";
import { templates as neoModernTemplates, settings as neoModernSettings } from "./neo-modern";
import { templates as neoStandardTemplates, settings as neoStandardSettings } from "./neo-standard";
import { templates as neoSwiftTemplates, settings as neoSwiftSettings } from "./neo-swift";
import { templates as standardTemplates, settings as standardSettings } from "./standard";
import { templates as swiftTemplates, settings as swiftSettings } from "./swift";
import { templates as watercolorTemplates, settings as watercolorSettings } from "./watercolor";


export const allLayouts: TemplateWithData[] = [
    ...blueprintTemplates,
    ...chalkboardTemplates,
    ...generalTemplates,
    ...modernTemplates,
    ...neoGeneralTemplates,
    ...neoModernTemplates,
    ...neoStandardTemplates,
    ...neoSwiftTemplates,
    ...standardTemplates,
    ...swiftTemplates,
    ...watercolorTemplates,
];


export const templates: TemplateLayoutsWithSettings[] = [
    {
        id: "blueprint",
        name: "Blueprint",
        description: blueprintSettings.description,
        settings: blueprintSettings as TemplateGroupSettings,
        layouts: blueprintTemplates,
    },
    {
        id: "chalkboard",
        name: "Chalkboard",
        description: chalkboardSettings.description,
        settings: chalkboardSettings as TemplateGroupSettings,
        layouts: chalkboardTemplates,
    },
    {
        id: "general",
        name: "General",
        description: generalSettings.description,
        settings: generalSettings as TemplateGroupSettings,
        layouts: generalTemplates,
    },
    {
        id: "modern",
        name: "Modern",
        description: modernSettings.description,
        settings: modernSettings as TemplateGroupSettings,
        layouts: modernTemplates,
    },
    {
        id: "neo-general",
        name: "Neo General",
        description: neoGeneralSettings.description,
        settings: neoGeneralSettings as TemplateGroupSettings,
        layouts: neoGeneralTemplates,
    },
    {
        id: "neo-modern",
        name: "Neo Modern",
        description: neoModernSettings.description,
        settings: neoModernSettings as TemplateGroupSettings,
        layouts: neoModernTemplates,
    },
    {
        id: "neo-standard",
        name: "Neo Standard",
        description: neoStandardSettings.description,
        settings: neoStandardSettings as TemplateGroupSettings,
        layouts: neoStandardTemplates,
    },
    {
        id: "neo-swift",
        name: "Neo Swift",
        description: neoSwiftSettings.description,
        settings: neoSwiftSettings as TemplateGroupSettings,
        layouts: neoSwiftTemplates,
    },
    {
        id: "standard",
        name: "Standard",
        description: standardSettings.description,
        settings: standardSettings as TemplateGroupSettings,
        layouts: standardTemplates,
    },
    {
        id: "swift",
        name: "Swift",
        description: swiftSettings.description,
        settings: swiftSettings as TemplateGroupSettings,
        layouts: swiftTemplates,
    },
    {
        id: "watercolor",
        name: "Watercolor",
        description: watercolorSettings.description,
        settings: watercolorSettings as TemplateGroupSettings,
        layouts: watercolorTemplates,
    },
];


// Helper to get templates by group ID
export function getTemplatesByTemplateName(templateId: string): TemplateWithData[] {
    const template = templates.find((t) => t.id === templateId);
    return template?.layouts || [];
}

export function getSchemaByTemplateId(templateId: string): any {
    const template = templates.find((t) => t.id === templateId);
    return template?.layouts.map(t => {
        return {
            id: t.layoutId,
            name: t.layoutName,
            description: t.layoutDescription,
            json_schema: t.schemaJSON,
        }
    }) || {};
}

export function getSettingsByTemplateId(templateId: string): TemplateGroupSettings | undefined {
    const template = templates.find((t) => t.id === templateId);
    return template?.settings || undefined;
}

// Helper to get template by layout ID
export function getTemplateByLayoutId(layoutId: string): TemplateWithData | undefined {
    return allLayouts.find((t) => t.layoutId === layoutId);
}

export function getLayoutByLayoutId(layout: string): TemplateWithData | undefined {
    const templateName = layout.split(':')[0]
    const template = templates.find((t) => t.id === templateName)
    if (template) {
        return template.layouts.find((t) => t.layoutId === layout);
    }
    return undefined;
}
